import type { EnemyStats, EnemyId } from './types';

export const ENEMY_DEFS: Record<EnemyId, EnemyStats> = {
  rifleman: {
    id: 'rifleman',
    name: 'Rifleman',
    hp: 22,
    moveSpeed: 70,
    damage: 6,
    attackCooldown: 1.4,
    attackRange: 320,
    preferredRange: 220,
    xpReward: 8,
    radius: 14,
    color: '#8d8aa3',
    telegraphMs: 260,
  },
  rusher: {
    id: 'rusher',
    name: 'Rusher',
    hp: 16,
    moveSpeed: 150,
    damage: 10,
    attackCooldown: 0.9,
    attackRange: 34,
    preferredRange: 0,
    xpReward: 7,
    radius: 13,
    color: '#ff5d7a',
  },
  shotgunner: {
    id: 'shotgunner',
    name: 'Shotgunner',
    hp: 30,
    moveSpeed: 95,
    damage: 5,
    attackCooldown: 1.7,
    attackRange: 150,
    preferredRange: 110,
    xpReward: 10,
    radius: 15,
    color: '#c9f73e',
    telegraphMs: 300,
  },
  sniper: {
    id: 'sniper',
    name: 'Sniper',
    hp: 18,
    moveSpeed: 55,
    damage: 16,
    attackCooldown: 2.6,
    attackRange: 560,
    preferredRange: 420,
    xpReward: 14,
    radius: 14,
    color: '#5cd0ff',
    telegraphMs: 650,
  },
  elite_rifleman: {
    id: 'elite_rifleman',
    name: 'Elite Rifleman',
    hp: 90,
    moveSpeed: 85,
    damage: 9,
    attackCooldown: 1.0,
    attackRange: 340,
    preferredRange: 240,
    xpReward: 40,
    radius: 19,
    color: '#8b6bff',
    isElite: true,
    telegraphMs: 220,
  },
};
