import type { GameDef } from '../types';

/**
 * Official registry of games. Add a new game by appending an entry here,
 * implementing a `render<Name>Game()` in `src/games/<id>/`, and wiring it
 * into `src/games/index.ts`'s GAME_RENDERERS map — pages (home, games grid)
 * render purely off this list.
 */
export const GAMES: GameDef[] = [
  {
    id: 'reaction',
    title: 'Reaction',
    category: 'REFLEKS',
    icon: '⚡',
    iconAsset: '/gameicons/reaction.png',
    description: 'Fem runder. Ét job: slå lyset. Ren refleks, rent pres.',
    scoreKind: 'reaction_ms',
    implemented: true,
  },
  {
    id: 'aim',
    title: 'Aim Trainer',
    category: 'PRÆCISION',
    icon: '🎯',
    iconAsset: '/gameicons/aim-trainer.png',
    description: 'Ram så mange mål som muligt på 30 sekunder.',
    scoreKind: 'aim_hits',
    implemented: true,
  },
  {
    id: 'memory',
    title: 'Memory',
    category: 'FOKUS',
    icon: '🧠',
    iconAsset: '/gameicons/memory.png',
    description: 'Husk stadig længere sekvenser.',
    scoreKind: 'memory_level',
    implemented: true,
  },
  {
    id: 'numberrush',
    title: 'Number Rush',
    category: 'HOVEDREGNING',
    icon: '🔢',
    iconAsset: '/gameicons/number-rush.png',
    description: 'Løs så mange stykker som muligt før tiden løber ud.',
    scoreKind: 'numberrush_score',
    implemented: true,
  },
  {
    id: 'snake',
    title: 'Snake',
    category: 'KLASSIKER',
    icon: '🟩',
    iconAsset: '/gameicons/snake.png',
    description: 'Den der startede det hele. Pas på ikke at bide dig selv.',
    scoreKind: 'snake_score',
    implemented: true,
  },
  {
    id: 'tactical',
    title: 'Breach Protocol',
    category: 'ROGUELITE',
    icon: '🪖',
    iconAsset: '/gameicons/breach-protocol.png',
    description: 'Ryd rum, byg dit loadout, overlev bossen. Auto-sigte roguelite i taktisk stil.',
    scoreKind: 'tactical_rooms',
    implemented: true,
  },
  {
    id: 'color',
    title: 'Color Match',
    category: 'PERCEPTION',
    icon: '🎨',
    iconAsset: '/gameicons/color-match.png',
    description: 'Match målfarven så præcist som muligt.',
    scoreKind: 'color_accuracy',
    implemented: true,
  },
  {
    id: 'stack',
    title: 'Stack Tower',
    category: 'TIMING',
    icon: '🧱',
    iconAsset: '/gameicons/stack-tower.png',
    description: 'Tap i det rette øjeblik og byg tårnet højere. Ét skævt hop, og det er slut.',
    scoreKind: 'stack_height',
    implemented: true,
  },
  {
    id: 'dash',
    title: 'Dash',
    category: 'OVERLEVELSE',
    icon: '💨',
    iconAsset: '/gameicons/dash.png',
    description: 'Ét tryk. Undgå forhindringerne så længe du kan.',
    scoreKind: 'dash_distance',
    implemented: true,
  },
  {
    id: 'merge',
    title: 'Merge',
    category: 'PUSLESPIL',
    icon: '🔢',
    iconAsset: '/gameicons/merge.png',
    description: 'Swipe for at flette ens tal sammen. Hvor højt kan du nå?',
    scoreKind: 'merge_tile',
    implemented: true,
  },
  {
    id: 'overclock',
    title: 'Overclock',
    category: 'RISIKO',
    icon: '⚛️',
    iconAsset: '/gameicons/overclock.png',
    description: 'Hold nede for at lade op, slip for at banke, men overloader kernen, mister du alt.',
    scoreKind: 'overclock_score',
    implemented: true,
  },
  {
    id: 'glitchgrid',
    title: 'Glitch Grid',
    category: 'SELEKTION',
    icon: '🐛',
    iconAsset: '/gameicons/glitch-grid.png',
    description: 'Tap glitch-felterne, undgå de korrupte. Combo giver flere point.',
    scoreKind: 'glitchgrid_score',
    implemented: true,
  },
  {
    id: 'pulse',
    title: 'Pulse',
    category: 'RYTME',
    icon: '🎧',
    iconAsset: '/gameicons/pulse.png',
    description: 'Tap i takt når toner rammer linjen. Ram præcist for combo.',
    scoreKind: 'pulse_score',
    implemented: true,
  },
  {
    id: 'dropzone',
    title: 'Drop Zone',
    category: 'HELD',
    icon: '🎱',
    iconAsset: '/gameicons/drop-zone.png',
    description: 'Sigt og slip kuglen ned gennem felterne, kant-boksene giver flest point.',
    scoreKind: 'dropzone_score',
    implemented: true,
  },
  {
    id: 'ruleswitch',
    title: 'Rule Breaker',
    category: 'HURTIG TÆNKNING',
    icon: '🔀',
    iconAsset: '/gameicons/rule-breaker.png',
    description: 'Sortér tal efter reglen, men reglen skifter uden varsel.',
    scoreKind: 'ruleswitch_score',
    implemented: true,
  },
  {
    id: 'wordrush',
    title: 'Word Rush',
    category: 'HURTIGSKRIVNING',
    icon: '⌨️',
    iconAsset: '/gameicons/word-rush.svg',
    description: 'Skriv ordet før tiden løber ud. Hvor mange når du?',
    scoreKind: 'wordrush_score',
    implemented: true,
  },
  {
    id: 'swerve',
    title: 'Swerve',
    category: 'UNDVIGELSE',
    icon: '🌀',
    iconAsset: '/gameicons/swerve.svg',
    description: 'Styr til siden og undgå blokkene. Farten stiger hele tiden.',
    scoreKind: 'swerve_time',
    implemented: true,
  },
  {
    id: 'pairs',
    title: 'Pairs',
    category: 'HUKOMMELSE',
    icon: '🃏',
    iconAsset: '/gameicons/pairs.svg',
    description: 'Vend kort, find parrene, slå uret.',
    scoreKind: 'pairs_score',
    implemented: true,
  },
  {
    id: 'oddoneout',
    title: 'Odd One Out',
    category: 'OPFATTELSE',
    icon: '🔎',
    iconAsset: '/gameicons/odd-one-out.svg',
    description: 'Find feltet der skiller sig ud, hurtigere for hver runde.',
    scoreKind: 'oddoneout_score',
    implemented: true,
  },
  {
    id: 'colossus',
    title: 'Colossus',
    category: 'BOSSKAMP',
    icon: '👁️',
    iconAsset: '/gameicons/colossus.svg',
    description: 'Stå tæt på kolossen for at gøre skade, undgå dens varslede angreb. Sejr eller død, din skade tæller.',
    scoreKind: 'colossus_damage',
    // Not ready yet — flip back to true once it's ready to publish. See router.ts's
    // "not implemented" guard for why this alone is enough to also block direct URL access.
    implemented: false,
  },
  {
    id: 'trajectory',
    title: 'Trajectory',
    category: 'FYSIK',
    icon: '🎈',
    iconAsset: '/gameicons/trajectory.svg',
    description: 'Træk tilbage og slip, sigt med tyngdekraft og ram så mange balloner som muligt på 8 skud.',
    scoreKind: 'trajectory_score',
    // Not ready yet — dragging the slingshot back can drag the browser window/viewport
    // instead, making it impossible to actually shoot. Flip back to true once fixed.
    implemented: false,
  },
  {
    id: 'tetris',
    title: 'Tetris',
    category: 'KLASSIKER',
    icon: '🧱',
    iconAsset: '/gameicons/tetris.svg',
    description: 'Den evige klassiker. Klar linjer, hold roen, hvor højt kan du undgå at bygge?',
    scoreKind: 'tetris_score',
    implemented: true,
  },
  {
    id: 'towerdefense',
    title: 'Ember Ward',
    category: 'TÅRNFORSVAR',
    icon: '🔥',
    iconAsset: '/gameicons/ember-ward.svg',
    description: 'Byg tårne, sænk horder af goblins, orcer og trolde. Hvor mange bølger holder du?',
    scoreKind: 'towerdefense_waves',
    implemented: true,
  },
];
